name: Auto Merge Release Branch

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  merge-release:
    if: github.event_name == 'workflow_dispatch' || startsWith(github.event.head_commit.message, 'Release v')

    permissions:
      contents: write

    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch origin

      - name: Checkout release branch
        run: git checkout release

      - name: Merge main into release
        run: git merge --ff-only origin/main

      - name: Push release branch
        run: git push origin release